### ISSUE TITLE
 hardwired file paths

### ISSUE THREAD

**Issue by looma** [Tzeak/Looma#1]
I found several issues with file paths:
1. some are absolute paths [e.g. /Backend/...] that should be relative
2. some file specifiers dont have the right folder [e.g. missing js/]
3. see attached email for more details
   [lesson planner issues - filepaths.rtfd.zip](https://github.com/Tzeak/Looma/files/330775/lesson.planner.issues.-.filepaths.rtfd.zip)

**Comment by Tzeak** [comment]
absolute paths have been changed to relative paths
